version: 2

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - formats: [ tar.gz ]

    # use zip for windows
    format_overrides:
      - goos: windows
        formats: [ zip ]
        
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"