name: Simple Build for Termux

on:
  workflow_dispatch: # Allows you to click a button to start

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Surge for Termux
        run: |
          # We use GOOS=android to prevent the SIGSYS error on Termux
          CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -ldflags="-s -w" -o surge-termux .

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: surge-termux-binary
          path: surge-termux
