name: Build Surge for Termux (No Benchmark)

on:
  workflow_dispatch: # Allows manual trigger via button

jobs:
  build:
    name: Build Android ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Binary
        run: |
          # GOOS=android fixes the "Bad system call" error
          # -ldflags "-s -w" makes the binary smaller
          env CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -ldflags "-s -w" -o surge .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: surge-termux
          path: surge
